export const APP_NAME = 'Meeting Tracker';
export const API_PORT = 8090;
export const API_URL = 'http://localhost:' + API_PORT;
export const EMPLOYEEID_PREFIX = 'WT';
export const EMPLOYEEID_MAX_LENGTH = 7;
export const ERROR_MESSAGE_CONTACT_SUPPORT = 'Some error has occurred. Please contact support at *****';
export const ERROR_MESSAGE_INVALID_CREDENTIALS = 'Invalid Credentials';
export const PASSWORD = 'admin';
export const USERNAME = 'admin';